### ISSUE TITLE
Invalid HTTP_HOST header error appears when accessing mozilla-pontoon.herokuapp.com

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2245]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1682302](https://bugzilla.mozilla.org/show_bug.cgi?id=1682302)
Bug Reporter: @mathjazz

We've never had Pontoon available at mozilla-pontoon.herokuapp.com (default Heroku URL). Recently however we started getting the following error when access to pontoon.mozilla.org is made through the default Heroku domain:

```
Invalid HTTP_HOST header: 'mozilla-pontoon.herokuapp.com'. You may need to add 'mozilla-pontoon.herokuapp.com' to ALLOWED_HOSTS.
[2020-12-14 13:48:20 +0000] [11] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/deprecation.py", line 113, in __call__
    response = self.process_request(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/app/.heroku/python/lib/python3.8/site-packages/django/http/request.py", line 137, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'mozilla-pontoon.herokuapp.com'. You may need to add 'mozilla-pontoon.herokuapp.com' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 161, in _get_token
    return request.session.get(CSRF_SESSION_KEY)
AttributeError: 'WSGIRequest' object has no attribute 'session'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 121, in get_exception_response
    response = callback(request, **{**param_dict, 'exception': exception})
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 200, in process_request
    csrf_token = self._get_token(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 163, in _get_token
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 161, in _get_token
    return request.session.get(CSRF_SESSION_KEY)
AttributeError: 'WSGIRequest' object has no attribute 'session'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/deprecation.py", line 114, in __call__
    response = response or self.get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1203, in _wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 95, in response_for_exception
    response = get_exception_response(request, get_resolver(get_urlconf()), 400, exc)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 124, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 490, in wrapper
    return _wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 483, in _wrapped
    return wrapped(request, resolver, exc_info)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 200, in process_request
    csrf_token = self._get_token(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 163, in _get_token
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 161, in _get_token
    return request.session.get(CSRF_SESSION_KEY)
AttributeError: 'WSGIRequest' object has no attribute 'session'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/deprecation.py", line 114, in __call__
    response = response or self.get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1203, in _wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 103, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 490, in wrapper
    return _wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 483, in _wrapped
    return wrapped(request, resolver, exc_info)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 142, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 544, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 200, in process_request
    csrf_token = self._get_token(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/middleware/csrf.py", line 163, in _get_token
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.

...
```

**Comment by mathjazz** [comment]
Adding an environment variable `ALLOWED_HOSTS` with a value of `mozilla-pontoon.herokuapp.com` fixes the problem on the prod instance.

**Comment by yoesak** [comment]
I'm experiencing with  this also although I already set ALLOWED_HOSTS to my domain, and also heroku

jango.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.

please help
