### ISSUE TITLE
Sync breaks with TypeError: 'builtin_function_or_method' object is not subscriptable

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2285]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1703748](https://bugzilla.mozilla.org/show_bug.cgi?id=1703748)
Bug Reporter: @mathjazz

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/application_celery.py", line 84, in wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/pontoon/sync/core.py", line 68, in wrapped_func
    return func(self, *args, **kwargs)
  File "/app/pontoon/sync/tasks.py", line 101, in sync_project
    sync_translations(
  File "/app/pontoon/sync/tasks.py", line 336, in sync_translations
    new_locales.append[locale.pk]
TypeError: 'builtin_function_or_method' object is not subscriptable
```

**Comment by potat0** [comment]
This was already fixed in https://github.com/mozilla/pontoon/pull/1914 ?

**Comment by mathjazz** [comment]
Indeed. See the comment in the PR, though:

> I'll keep the bug open to increase test coverage and catch the error early.
