### ISSUE TITLE
Downloading TMX fails

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2821]
This is failing from both CLI with Curl, and from Pontoon. This started in the last 24 hours

```
$ curl -o it.all-projects.tmx --compressed https://pontoon.mozilla.org/translation-memory/it.all-projects.tmx

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1817k    0 1817k    0     0   200k      0 --:--:--  0:00:09 --:--:--  405k
curl: (18) transfer closed with outstanding read data remaining
```

No code changes were pushed to prod or stage, but there was work on the DB for Relay.

```
 Apr 19 13:09:59 mozilla-pontoon heroku/router sock=backend at=error code=H18 desc="Server Request Interrupted" method=GET path="/translation-memory/it.all-projects.tmx" host=pontoon.mozilla.org request_id=305e7665-27a6-4c01-833e-1e866acd2ad1 fwd="95.90.246.29" dyno=web.1 connect=0ms service=3411ms status=503 bytes= protocol=https
Apr 19 13:09:59 mozilla-pontoon app/web.1 [2023-04-19 13:09:59 +0000] [9] [ERROR] Error handling request
Apr 19 13:09:59 mozilla-pontoon app/web.1 Traceback (most recent call last):
Apr 19 13:09:59 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
Apr 19 13:09:59 mozilla-pontoon app/web.1     for item in respiter:
Apr 19 13:09:59 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/api/wsgi_application.py", line 47, in __iter__
Apr 19 13:09:59 mozilla-pontoon app/web.1     for item in self.generator:
Apr 19 13:09:59 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/api/wsgi_application.py", line 454, in __iter__
Apr 19 13:09:59 mozilla-pontoon app/web.1     for data in self.iterable:
Apr 19 13:09:59 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/utils/text.py", line 304, in compress_sequence
Apr 19 13:09:59 mozilla-pontoon app/web.1     for item in sequence:
Apr 19 13:09:59 mozilla-pontoon app/web.1   File "/app/pontoon/base/utils.py", line 525, in build_translation_memory_file
Apr 19 13:09:59 mozilla-pontoon app/web.1     tuid = ":".join((project_slug, resource_path, slugify(key)))
Apr 19 13:09:59 mozilla-pontoon app/web.1 TypeError: sequence item 1: expected str instance, NoneType found
```

Downloads work fine from stage.

**Comment by flodolo** [comment]
That's expected, given the use of project configuration.

**Comment by mathjazz** [comment]
This should be fixed now.

During the migration of Firefox Relay, TM entries of the `brands.ftl` Resource lost their `Entity` references. They have been restored now.

**Comment by flodolo** [comment]
> During the migration of Firefox Relay

Is the process for these migrations documented anywhere? What can be done to avoid this repeating in the future?

**Comment by mathjazz** [comment]
This particular migration was different from others, because it moved strings from one file to many others. And there was plenty of them and plenty of manual work. Which triggered a human error.

The best way to prevent such errors going forward is to automate the process as much as possible by fixing #2014, #2087 and the likes.

There is no one process for migrations. But I should start adding scripts to https://github.com/mozilla-l10n/pontoon-scripts/ and possibly amending them for each migration.
